/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Signal {
    id: string;
    currentPrice: number;
    direction: Direction;
    takeProfit: number;
    reasoning: string;
    stopLoss: number;
    estimatedHours: bigint;
    timestamp: bigint;
    coinName: string;
    entryPrice: number;
    hitTarget: boolean;
    confidence: bigint;
    symbol: string;
    profitPercent: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum Direction {
    long_ = "long",
    short_ = "short"
}
export interface backendInterface {
    addSignal(id: string, coinName: string, symbol: string, currentPrice: number, entryPrice: number, takeProfit: number, stopLoss: number, confidence: bigint, estimatedHours: bigint, direction: Direction, reasoning: string): Promise<void>;
    fetchCryptoPrices(symbol: string): Promise<string>;
    getHighProfitSignals(): Promise<Array<Signal>>;
    getSignals(): Promise<Array<Signal>>;
    rescan(): Promise<void>;
    scheduleRescan(): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateSignalAccuracy(id: string, hit: boolean): Promise<void>;
}
import type { Direction as _Direction, Signal as _Signal } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSignal(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: number, arg7: bigint, arg8: bigint, arg9: Direction, arg10: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSignal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg9), arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSignal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg9), arg10);
            return result;
        }
    }
    async fetchCryptoPrices(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCryptoPrices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCryptoPrices(arg0);
            return result;
        }
    }
    async getHighProfitSignals(): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHighProfitSignals();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHighProfitSignals();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSignals(): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignals();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignals();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async rescan(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rescan();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescan();
            return result;
        }
    }
    async scheduleRescan(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleRescan();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleRescan();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateSignalAccuracy(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSignalAccuracy(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSignalAccuracy(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Direction_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Signal_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Signal): Signal {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    currentPrice: number;
    direction: _Direction;
    takeProfit: number;
    reasoning: string;
    stopLoss: number;
    estimatedHours: bigint;
    timestamp: bigint;
    coinName: string;
    entryPrice: number;
    hitTarget: boolean;
    confidence: bigint;
    symbol: string;
    profitPercent: number;
}): {
    id: string;
    currentPrice: number;
    direction: Direction;
    takeProfit: number;
    reasoning: string;
    stopLoss: number;
    estimatedHours: bigint;
    timestamp: bigint;
    coinName: string;
    entryPrice: number;
    hitTarget: boolean;
    confidence: bigint;
    symbol: string;
    profitPercent: number;
} {
    return {
        id: value.id,
        currentPrice: value.currentPrice,
        direction: from_candid_Direction_n6(_uploadFile, _downloadFile, value.direction),
        takeProfit: value.takeProfit,
        reasoning: value.reasoning,
        stopLoss: value.stopLoss,
        estimatedHours: value.estimatedHours,
        timestamp: value.timestamp,
        coinName: value.coinName,
        entryPrice: value.entryPrice,
        hitTarget: value.hitTarget,
        confidence: value.confidence,
        symbol: value.symbol,
        profitPercent: value.profitPercent
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    long: null;
} | {
    short: null;
}): Direction {
    return "long" in value ? Direction.long : "short" in value ? Direction.short : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Signal>): Array<Signal> {
    return value.map((x)=>from_candid_Signal_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Direction_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): _Direction {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): {
    long: null;
} | {
    short: null;
} {
    return value == Direction.long ? {
        long_: null
    } : value == Direction.short ? {
        short_: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
